/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    IconUsageGuide: typeof import('./src/components/IconUsageGuide.vue')['default']
    IMdiCheckCircleOutline: typeof import('~icons/mdi/check-circle-outline')['default']
    IMdiClose: typeof import('~icons/mdi/close')['default']
    IMdiDownload: typeof import('~icons/mdi/download')['default']
    IMdiHome: typeof import('~icons/mdi/home')['default']
    IMdiMinus: typeof import('~icons/mdi/minus')['default']
    IMdiResize: typeof import('~icons/mdi/resize')['default']
    IMdiWindowMaximize: typeof import('~icons/mdi/window-maximize')['default']
    IMdiWindowRestore: typeof import('~icons/mdi/window-restore')['default']
    ModalContextProbe: typeof import('./src/components/Modal/ModalContextProbe.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    YlModal: typeof import('./src/components/Modal/YlModal.vue')['default']
    YlModalHost: typeof import('./src/components/Modal/YlModalHost.vue')['default']
  }
}
